# Dependabot configuration file.
# See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates
version: 2

enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "cloud_firestore_type_adapters"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "example/sembast_db_explorer_app"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "notepad_stress_app"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "repo_support"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "sembast_db_explorer"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "sembast_flutter"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
